global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "stream-processor"
    static_configs:
      - targets: ["stream-processor:8000"]
  - job_name: "producer"
    static_configs:
      - targets: ["producer:8000"]
  - job_name: "event-sink"
    static_configs:
      - targets: ["event-sink:8000"]
